### ISSUE TITLE
White screen & composer.json can't be found

### ISSUE THREAD

**Issue by diejorm** [checkout/checkout-prestashop1.7-plugin#19]
Hi there,

I tried to install this module today within a Google Cloud's Bitnami certified Prestashop V1.7.6. 

1. The "module manager screen" goes completely white.
2. When running the command you get:
......... modules/checkoutcom$ composer install --no-dev
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
Composer could not find a composer.json file in 
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

Of course, I checked and the composer.json file is actually there...

Any clue about what I might be doing wrong? 

Thanks in advance!

**Comment by avish-bisbeehurry-cko** [comment]
@diejorm can you confirm if this is still an issue.
